### ISSUE TITLE
the QC flags of Ozflux sites

### ISSUE THREAD

**Issue by Mbnl1197** [aukkola/PLUMBER2#2]
Hello！
I'm using this data for research.But I don't know what QC flags stands for in each value in ozflux.
Can you help me?
THANKS！

**Comment by aukkola** [comment]
Hello,

The description of the QC flags can be found in the global attributes of the NetCDF files. Alternatively, you can find a list here (line 203 onwards):
https://github.com/aukkola/FluxnetLSM/blob/master/R/Utility_functions.R

Thanks,
Anna
